In [ ]:

import numpy as np
from scipy.spatial import distance
from scipy.spatial.distance import cosine
from scipy.spatial.distance import pdist
from scipy.spatial.distance import squareform
from gower import gower_matrix
import pandas as pd
data = [
    ["Alice", 28, "Female", "Engineer", 75000, 65, 140],
    ["Bob", 32, "Male", "Data Scientist", 85000, 70, 180],
    ["Charlie", 23, "Male", "Student", 15000, 68, 160],
    ["David", 40, "Male", "Doctor", 120000, 72, 200],
    ["Eve", 35, "Female", "Lawyer", 90000, 63, 130]
]
age_income_data = np.array([[row[1], row[4]] for row in data])
age_height_weight_data = np.array([[row[1], row[5], row[6]] for row in data])
income_height_weight_data = np.array([[row[4], row[5], row[6]] for row in data])
gender_occupation_data = np.array([[row[2], row[3]] for row in data])
manhattan_distance = np.zeros((len(data), len(data)))
for i in range(len(data)):
    for j in range(len(data)):
        manhattan_distance[i, j] = distance.cityblock(age_income_data[i], age_income_data[j])
euclidean_distance = distance.pdist(age_height_weight_data, metric='euclidean')
euclidean_distance = distance.squareform(euclidean_distance)
cosine_similarity = pdist(income_height_weight_data, metric='cosine')
cosine_similarity = 1 - squareform(cosine_similarity)
def jaccard_similarity(set1, set2):
    intersection = len(set1.intersection(set2))
    union = len(set1.union(set2))
    return intersection / union

jaccard_similarity_matrix = np.zeros((len(gender_occupation_data), len(gender_occupation_data)))
for i in range(len(gender_occupation_data)):
    for j in range(len(gender_occupation_data)):
        jaccard_similarity_matrix[i, j] = jaccard_similarity(set(gender_occupation_data[i]), set(gender_occupation_data[j]))
df = pd.DataFrame(data, columns=["Name", "Age", "Gender", "Occupation", "Income", "Height", "Weight"])
gower_dist_matrix = gower_matrix(df)
print("Manhattan Distance:")
print(manhattan_distance)
print("\nEuclidean Distance:")
print(euclidean_distance)
print("\nCosine Similarity:")
print(cosine_similarity)
print("\nJaccard Similarity:")
print(jaccard_similarity_matrix)
print("\nGower Distance:")
print(gower_dist_matrix)



Manhattan Distance:
[[     0.  10004.  60005.  45012.  15007.]
 [ 10004.      0.  70009.  35008.   5003.]
 [ 60005.  70009.      0. 105017.  75012.]
 [ 45012.  35008. 105017.      0.  30005.]
 [ 15007.   5003.  75012.  30005.      0.]]

Euclidean Distance:
[[ 0.         40.5092582  20.83266666 61.58733636 12.36931688]
 [40.5092582   0.         22.02271555 21.63330765 50.57667447]
 [20.83266666 22.02271555  0.         43.64630569 32.69556545]
 [61.58733636 21.63330765 43.64630569  0.         70.75309181]
 [12.36931688 50.57667447 32.69556545 70.75309181  0.        ]]

Cosine Similarity:
[[1.         0.99999997 0.99995456 0.99999994 0.9999999 ]
 [0.99999997 1.         0.99995658 0.99999987 0.99999977]
 [0.99995456 0.99995658 1.         0.99995177 0.99995013]
 [0.99999994 0.99999987 0.99995177 1.         0.99999997]
 [0.9999999  0.99999977 0.99995013 0.99999997 1.        ]]

Jaccard Similarity:
[[1.         0.         0.         0.         0.33333333]
 [0.         1.         0.33333333 0.